### ISSUE TITLE
Removing DMF

### ISSUE THREAD

**Issue by selimsami** [selimsami/qforce_examples#7]
@xiki-tempula , I guess the DMF examples can now be safely removed?

**Comment by xiki-tempula** [comment]
Sorry, I didn't make it very clear. The NBO6 and DMF have already been removed.

**Comment by selimsami** [comment]
Not in Gaussian and xTB directories and` __init__.py`

**Comment by xiki-tempula** [comment]
@selimsami Do you mind restart the CI in the qforce to check if all the tests are passing?

**Comment by selimsami** [comment]
All works now, thanks!
